[package]
name = "gowm"
version = "0.1.0"
authors = ["xiongmaomaomao <pasapasa.va1104@gmail.com@gmail.com>"]

[dependencies]
clap = "2"
colored = "1.3"
log = "0.3"
env_logger = "0.3"
hyper = "0.9"
rustc-serialize = "0.3"
toml = "0.2"
